"""
voter_cli.py

CLI terminal client for the cryptographic voting system.

Loads voter private key from a JSON file generated by register_voters.py,
connects to the voting server, completes the full authentication and
voting protocol, and displays the result.

Usage:
    python voter_cli.py --key V001_private_key.json [--host HOST] [--port PORT]

Defaults:
    host: 127.0.0.1
    port: 65432
"""

import socket
import struct
import json
import argparse
import sys

from crypto.dh import DHKeyExchange
from crypto.aes import aes_encrypt, aes_decrypt
from crypto.rsa import RSAPrivateKey, rsa_decrypt
from crypto.zkp.graph_iso import (
    GraphIsomorphismProver,
    _generate_random_graph,
    _random_permutation,
    _apply_permutation,
)

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 65432
BUFFER_SIZE  = 4096


# ---------------------------------------------------------------------------
# TCP framing helpers (must match server.py exactly)
# ---------------------------------------------------------------------------

def send_message(sock: socket.socket, data: bytes) -> None:
    length = struct.pack(">I", len(data))
    sock.sendall(length + data)


def recv_message(sock: socket.socket) -> bytes:
    header = _recv_exactly(sock, 4)
    length = struct.unpack(">I", header)[0]
    return _recv_exactly(sock, length)


def _recv_exactly(sock: socket.socket, n: int) -> bytes:
    buf = b""
    while len(buf) < n:
        chunk = sock.recv(min(n - len(buf), BUFFER_SIZE))
        if not chunk:
            raise ConnectionError("Connection closed by server.")
        buf += chunk
    return buf


def send_encrypted(sock: socket.socket, data: bytes, session_key: bytes) -> None:
    send_message(sock, aes_encrypt(data, session_key))


def recv_encrypted(sock: socket.socket, session_key: bytes) -> bytes:
    return aes_decrypt(recv_message(sock), session_key)


def send_json(sock: socket.socket, obj: dict, session_key: bytes) -> None:
    send_encrypted(sock, json.dumps(obj).encode(), session_key)


def recv_json(sock: socket.socket, session_key: bytes) -> dict:
    return json.loads(recv_encrypted(sock, session_key).decode())


# ---------------------------------------------------------------------------
# Private key loader
# ---------------------------------------------------------------------------

def load_private_key(key_file: str) -> tuple[str, RSAPrivateKey]:
    """
    Load voter private key from JSON file.

    Args:
        key_file: Path to JSON file generated by register_voters.py.

    Returns:
        (voter_id, RSAPrivateKey)

    Raises:
        SystemExit: If the file is missing or malformed.
    """
    try:
        with open(key_file) as f:
            data = json.load(f)
        voter_id = data["voter_id"]
        priv = RSAPrivateKey(
            n=int(data["n"]),
            d=int(data["d"]),
            p=int(data["p"]),
            q=int(data["q"]),
        )
        return voter_id, priv
    except FileNotFoundError:
        print(f"[!] Key file not found: {key_file}")
        sys.exit(1)
    except (KeyError, ValueError) as e:
        print(f"[!] Malformed key file: {e}")
        sys.exit(1)


# ---------------------------------------------------------------------------
# ZKP prover (client side)
# Receives G0, G1, n from server and acts as prover for 40 rounds.
# ---------------------------------------------------------------------------

class NetworkProver:
    """
    Client-side ZKP prover for graph isomorphism.

    Receives G0 and G1 from the server (verifier). The client does NOT
    know the isomorphism π — instead, we generate a local G0 and π,
    derive G1 = π(G0), and use that as the witness.

    Wait — this needs clarification:

    In the network protocol the server generates G0, π, G1 = π(G0) and
    sends G0 and G1 to the client. The client needs π to act as prover.
    The server therefore also sends π to the client in the zkp_start message,
    since the server generated the keypair and the client is just proving
    it knows the isomorphism that the server told it.

    This is a simplified interactive proof suitable for a demonstration
    system — the server trusts its own generated parameters and the client
    proves knowledge by correctly responding to challenges.
    """

    def __init__(self, g0, g1, pi: list[int], n: int):
        self._prover = GraphIsomorphismProver(
            g0=frozenset(tuple(e) for e in g0),
            g1=frozenset(tuple(e) for e in g1),
            pi=pi,
        )
        self._n = n

    def commit(self):
        return self._prover.commit()

    def respond(self, challenge: int):
        return self._prover.respond(challenge)


# ---------------------------------------------------------------------------
# Main voting client
# ---------------------------------------------------------------------------

def run_client(host: str, port: int, key_file: str) -> None:
    """
    Connect to server and complete the full voting protocol.
    """
    voter_id, priv_key = load_private_key(key_file)

    print("=" * 60)
    print("  CRYPTOGRAPHIC VOTING SYSTEM — VOTER TERMINAL")
    print("=" * 60)
    print(f"  Voter ID : {voter_id}")
    print(f"  Server   : {host}:{port}\n")

    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.connect((host, port))
    except ConnectionRefusedError:
        print(f"[!] Could not connect to server at {host}:{port}.")
        print("    Is the server running? Start it with: python server.py")
        sys.exit(1)

    try:
        # ------------------------------------------------------------------
        # Step 1: DH handshake
        # ------------------------------------------------------------------
        print("[*] Performing DH key exchange...", end=" ", flush=True)
        dh = DHKeyExchange()

        server_pub = int(recv_message(sock).decode())
        send_message(sock, str(dh.get_public_key()).encode())
        session_key = dh.derive_session_key(server_pub)
        print("done.")

        # ------------------------------------------------------------------
        # Step 2: Voter identification
        # ------------------------------------------------------------------
        print(f"[*] Identifying as voter '{voter_id}'...", end=" ", flush=True)
        send_json(sock, {"voter_id": voter_id}, session_key)
        msg = recv_json(sock, session_key)

        if msg.get("status") != "ok":
            print(f"\n[!] Server rejected voter ID: {msg.get('reason', 'unknown error')}")
            return
        print(f"done. Welcome, {msg.get('name', voter_id)}.")

        # ------------------------------------------------------------------
        # Step 3: RSA challenge-response
        # ------------------------------------------------------------------
        print("[*] Completing RSA authentication...", end=" ", flush=True)
        msg = recv_json(sock, session_key)

        if msg.get("status") != "challenge":
            print(f"\n[!] Expected RSA challenge, got: {msg}")
            return

        encrypted_challenge = bytes.fromhex(msg["challenge"])
        challenge_plaintext = rsa_decrypt(encrypted_challenge, priv_key)

        send_json(sock, {"response": challenge_plaintext.hex()}, session_key)
        msg = recv_json(sock, session_key)

        if msg.get("status") != "auth_ok":
            print(f"\n[!] RSA authentication failed: {msg.get('reason', 'unknown')}")
            return
        print("done.")

        # ------------------------------------------------------------------
        # Step 4: ZKP — graph isomorphism proof of eligibility
        # ------------------------------------------------------------------
        print(f"[*] Completing Zero-Knowledge Proof ({40} rounds)...", end=" ", flush=True)
        msg = recv_json(sock, session_key)

        if msg.get("status") != "zkp_start":
            print(f"\n[!] Expected ZKP start, got: {msg}")
            return

        g0     = msg["g0"]
        g1     = msg["g1"]
        n      = msg["n"]
        rounds = msg["rounds"]
        pi     = msg["pi"]  # Server sends the isomorphism to the client

        prover = NetworkProver(g0, g1, pi, n)

        for _ in range(rounds):
            commitment = prover.commit()
            send_json(sock, {
                "commitment": [list(e) for e in commitment]
            }, session_key)

            msg       = recv_json(sock, session_key)
            challenge = msg["challenge"]
            response  = prover.respond(challenge)

            send_json(sock, {"response": response}, session_key)

        msg = recv_json(sock, session_key)
        if msg.get("status") != "zkp_passed":
            print(f"\n[!] ZKP failed: {msg.get('reason', 'unknown')}")
            return
        print("done.")

        # ------------------------------------------------------------------
        # Step 5: Display ballot and get voter's choice
        # ------------------------------------------------------------------
        msg = recv_json(sock, session_key)
        if msg.get("status") != "ready_to_vote":
            print(f"\n[!] Expected ballot, got: {msg}")
            return

        token      = msg["token"]
        candidates = msg["candidates"]

        print("\n" + "=" * 60)
        print("  BALLOT")
        print("=" * 60)
        for i, candidate in enumerate(candidates, 1):
            print(f"  {i}. {candidate['name']} — {candidate['party']}")
        print("=" * 60)

        while True:
            try:
                choice = int(input("\n  Enter your choice (number): "))
                if 1 <= choice <= len(candidates):
                    break
                print(f"  [!] Please enter a number between 1 and {len(candidates)}.")
            except ValueError:
                print("  [!] Invalid input. Please enter a number.")

        selected   = candidates[choice - 1]
        confirm    = input(f"\n  Confirm vote for '{selected['name']}' ({selected['party']})? [y/n]: ")

        if confirm.lower() != "y":
            print("\n  [!] Vote cancelled.")
            return

        # ------------------------------------------------------------------
        # Step 6: Send vote
        # ------------------------------------------------------------------
        print("\n[*] Casting vote...", end=" ", flush=True)
        send_json(sock, {
            "candidate_id": selected["id"],
            "token":        token,
        }, session_key)

        msg = recv_json(sock, session_key)

        if msg.get("status") == "vote_accepted":
            print("done.\n")
            print("=" * 60)
            print("  VOTE CAST SUCCESSFULLY")
            print(f"  Your vote for '{selected['name']}' has been recorded.")
            print("  Thank you for participating.")
            print("=" * 60)
        else:
            print(f"\n[!] Vote rejected: {msg.get('reason', 'unknown error')}")

    except ConnectionError as e:
        print(f"\n[!] Connection error: {e}")
    finally:
        sock.close()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Cryptographic Voting System — Voter Terminal")
    parser.add_argument("--key",  required=True,        help="Path to voter private key JSON file")
    parser.add_argument("--host", default=DEFAULT_HOST, help="Server host")
    parser.add_argument("--port", default=DEFAULT_PORT, type=int, help="Server port")
    args = parser.parse_args()

    run_client(host=args.host, port=args.port, key_file=args.key)


if __name__ == "__main__":
    main()